// This script contains the comprehensive career data for all careers in ACCESS
// Each career follows the 11-section framework established for Medicine & Surgery

export const comprehensiveCareerData = {
  // Nursing
  "d-mhs-003": {
    aboutCareer: "Nursing is a profession dedicated to caring for patients across all healthcare settings. Nurses are the backbone of healthcare systems, providing direct patient care, health education, and emotional support. In Kenya, nurses work in hospitals, health centres, clinics, research institutions, and community health programmes. The nursing profession is evolving toward advanced practice with specialized roles in management, education, and research.",
    academicStructure: "The Bachelor of Science in Nursing is a 4-year programme consisting of 2 years of nursing theory and biological sciences, followed by 2 years of clinical placement in various hospital departments. Students complete clinical rotations in medical, surgical, paediatric, obstetric, psychiatric, and community health settings. Final year includes management modules and preparation for registration with the Nursing Council of Kenya.",
    technicalSkills: [
      "Patient assessment and monitoring",
      "Medication administration and nursing care",
      "Wound care and infection prevention",
      "Vital signs monitoring and interpretation",
      "IV therapy and venepuncture",
      "Electronic health records management",
      "Healthcare informatics",
      "First aid and emergency care",
    ],
    softSkills: [
      "Patient communication and counseling",
      "Empathy and compassion",
      "Teamwork and collaboration",
      "Leadership in healthcare teams",
      "Time management and organization",
      "Stress management and resilience",
      "Cultural sensitivity",
      "Attention to detail",
    ],
    careerPathways: [
      { title: "Hospital Nursing", description: "Work in hospital wards managing patient care in medical, surgical, ICU, or emergency departments." },
      { title: "Community Health Nursing", description: "Provide primary healthcare at community level, health promotion, and disease prevention in villages and health centres." },
      { title: "Specialization Pathways", description: "Pursue specialized nursing roles in oncology, critical care, paediatrics, midwifery, or psychiatry." },
      { title: "Nursing Management", description: "Progress to nurse manager, ward supervisor, or hospital nursing administrator roles." },
      { title: "Teaching & Education", description: "Teach in nursing schools or develop healthcare education programmes." },
      { title: "Public Health Nursing", description: "Work with government health departments on immunization, maternal health, and disease surveillance." },
    ],
    thingsToConsider: [
      { challenge: "High Emotional Demands", description: "Dealing with suffering, death, and trauma regularly can be emotionally exhausting. Strong coping mechanisms are essential." },
      { challenge: "Physically Demanding", description: "Long shifts, standing for extended periods, and lifting patients can lead to back injuries and fatigue." },
      { challenge: "Shift Work", description: "Nursing requires 24/7 coverage. Night shifts, weekends, and on-call duties are standard." },
      { challenge: "Relatively Lower Pay", description: "Compared to doctors, nurses earn less despite similar education length. Private practice earnings vary." },
      { challenge: "Scope Limitations", description: "In Kenya, nurses have limited prescribing authority. Advanced practice nursing is still developing." },
    ],
    detailedInstitutions: [
      { type: "public", name: "Kenyatta University - School of Nursing", location: "Nairobi", notes: "Leading nursing education institution" },
      { type: "public", name: "Moi University - School of Nursing", location: "Eldoret", notes: "Strong clinical training partnerships" },
      { type: "public", name: "Kenya Methodist University - School of Nursing", location: "Nairobi", notes: "Well-equipped nursing facilities" },
      { type: "public", name: "Masinde Muliro University - School of Nursing", location: "Kakamega", notes: "Community health focus" },
      { type: "private", name: "Mount Kenya University - School of Nursing", location: "Nairobi", notes: "Accredited private nursing programme" },
    ],
    clusterRequirements: "Compulsory: English/Kiswahili. Core Sciences: Biology (B+), Chemistry (B+), Mathematics/Physics (B). Mean grade B+ (plus) from best four subjects.",
    cutoffHistory: [
      { year: 2024, ranges: { high: 42, mid: 39, low: 37 }, notes: "High demand for nurses continues." },
      { year: 2023, ranges: { high: 41, mid: 38, low: 36 }, notes: "Consistent admission rates." },
      { year: 2022, ranges: { high: 40, mid: 37, low: 35 }, notes: "Standard admission year." },
    ],
    jobMarketTrends: {
      demandOutlook: "Kenya faces a critical nursing shortage with high demand across public and private sectors. The WHO recommends 1 nurse per 500 people, but Kenya has only 1 per 1,000+. This shortage creates excellent job security.",
      trends: [
        "Rapid expansion of private healthcare creating nursing positions",
        "Government initiatives on universal healthcare increasing nurse demand",
        "Growing specialization in ICU, oncology, and critical care nursing",
        "Community health worker integration creating leadership roles for nurses",
        "Telemedicine and digital health creating new nursing opportunities",
      ],
      challenges: [
        "Low government sector salaries compared to private hospitals",
        "Limited specialization opportunities in some regions",
        "High burnout rates from understaffing",
        "Limited career progression in government sector",
        "Brain drain to foreign countries for better opportunities",
      ],
    },
    salaryInsights: {
      entryLevel: "KES 35,000 - 55,000/month",
      midCareer: "KES 80,000 - 140,000/month",
      seniorLevel: "KES 150,000 - 200,000+/month",
    },
    funFacts: [
      { fact: "Kenya's nursing profession is predominantly female, with men comprising only about 15% of nurses.", category: "kenya-specific" },
      { fact: "The Nursing Council of Kenya, established in 1964, is one of the oldest regulatory bodies for nurses in Africa.", category: "historical" },
      { fact: "Community health nurses in Kenya have been instrumental in improving maternal mortality rates through home-based care.", category: "kenya-specific" },
      { fact: "Kenya's Health and Social Care Workers Union has over 100,000 registered nurses as members.", category: "kenya-specific" },
      { fact: "The average Kenyan nurse works 60+ hours per week in public hospitals due to staffing shortages.", category: "surprising" },
    ],
  },

  // Dentistry
  "d-mhs-004": {
    aboutCareer: "Dentistry is the healthcare profession focused on oral health, treating teeth, gums, and oral tissues. Dentists diagnose and treat dental diseases, perform preventive care, and provide cosmetic treatments. In Kenya, dentists work in private practices, government hospitals, teaching institutions, and research. The profession is growing with increasing demand for quality dental care.",
    academicStructure: "The BDS programme is 6 years of full-time study: 2 years of pre-clinical (anatomy, physiology, biochemistry), 2 years of para-clinical (oral pathology, pharmacology, prosthetics), and 2 years of clinical practice in dental clinics. Students treat patients under supervision and complete electives. After graduation, a 6-month internship is required before registration.",
    technicalSkills: [
      "Diagnostic teeth examination and X-ray interpretation",
      "Restorative dentistry (fillings and crowns)",
      "Oral surgery and tooth extraction",
      "Orthodontics and teeth alignment",
      "Periodontal disease treatment",
      "Dental prosthetics and denture fabrication",
      "Sterilization and infection control",
      "Dental radiography and imaging",
    ],
    softSkills: [
      "Patient communication and anxiety management",
      "Manual dexterity and hand-eye coordination",
      "Attention to detail",
      "Business management (for private practice)",
      "Leadership in dental teams",
      "Ethical practice",
      "Time management",
      "Problem-solving",
    ],
    careerPathways: [
      { title: "Private Dental Practice", description: "Own and operate a dental clinic. This is the most common path for dentists in Kenya with potential for high income." },
      { title: "Hospital Dentistry", description: "Work in government or private hospitals providing advanced dental care and managing dental emergencies." },
      { title: "Specialization", description: "Pursue specialties in orthodontics, periodontics, oral surgery, or prosthodontics through postgraduate training." },
      { title: "Public Health Dentistry", description: "Work on oral health promotion, school dental health programmes, and community dental care." },
      { title: "Dental Education", description: "Teach in dental schools or conduct dental research at universities." },
      { title: "Dental Industry", description: "Work with dental equipment manufacturers or pharmaceutical companies on product development." },
    ],
    thingsToConsider: [
      { challenge: "High Setup Costs", description: "Starting a dental practice requires significant investment in equipment, sterilization systems, and clinic setup (KES 2-5 million)." },
      { challenge: "Competitive Market", description: "Urban areas have high dentist-to-population ratios. Competition for patients is intense, especially in Nairobi." },
      { challenge: "Patient Anxiety", description: "Many patients fear dental procedures. Managing anxious patients requires patience and excellent communication." },
      { challenge: "Physical Strain", description: "Long hours in bent posture can cause neck, back, and shoulder problems. Repetitive strain is common." },
      { challenge: "Infection Risk", description: "Dealing with blood and saliva requires strict infection control protocols. Occupational hazards exist." },
    ],
    detailedInstitutions: [
      { type: "public", name: "University of Nairobi - School of Dentistry", location: "Nairobi", notes: "Only public dental school in Kenya" },
      { type: "public", name: "Moi University - School of Dentistry", location: "Eldoret", notes: "Recently established dental programme" },
      { type: "private", name: "Mount Kenya University - School of Dentistry", location: "Nairobi", notes: "Accredited private dental school" },
      { type: "private", name: "International Medical University", location: "Nairobi", notes: "Accredited international dental programme" },
    ],
    clusterRequirements: "Compulsory: English/Kiswahili. Core Sciences: Biology (A), Chemistry (A), Physics/Mathematics (B+). Mean grade A- (minus) or above from best four subjects.",
    cutoffHistory: [
      { year: 2024, ranges: { high: 46, mid: 43, low: 41 }, notes: "Highly competitive alongside medicine." },
      { year: 2023, ranges: { high: 45, mid: 42, low: 40 }, notes: "Limited slots increase competition." },
      { year: 2022, ranges: { high: 44, mid: 41, low: 39 }, notes: "Consistent high cutoffs." },
    ],
    jobMarketTrends: {
      demandOutlook: "Dental services in Kenya are in high demand but concentrated in urban areas. Private practice opportunities are abundant for those who can invest. Government dental positions are limited.",
      trends: [
        "Growing demand for cosmetic dentistry in urban areas",
        "Expansion of dental clinics in shopping malls and wellness centres",
        "Increasing awareness of oral health importance",
        "Growth of dental tourism potential in Kenya",
        "Private insurance covering dental services",
      ],
      challenges: [
        "Rural areas severely underserved with few dentists",
        "Patient affordability issues affecting demand",
        "High competition in urban markets",
        "Limited government sector employment",
        "Irregular patient flow in private practice",
      ],
    },
    salaryInsights: {
      entryLevel: "KES 45,000 - 75,000/month (employed); Variable in private practice",
      midCareer: "KES 150,000 - 250,000/month (established private practice)",
      seniorLevel: "KES 300,000+/month (successful dental practices)",
    },
    funFacts: [
      { fact: "Kenya's first dental school was established at the University of Nairobi in 1988.", category: "historical" },
      { fact: "Only about 1 in 10 Kenyans regularly visit a dentist, indicating huge untapped market potential.", category: "kenya-specific" },
      { fact: "Cosmetic dentistry and teeth whitening are among the fastest-growing dental services in urban Kenya.", category: "surprising" },
      { fact: "Most Kenyans' first dental visit occurs when they have an emergency (toothache) rather than for prevention.", category: "kenya-specific" },
      { fact: "Dental anxiety is so common in Kenya that patient education is a major part of a dentist's job.", category: "surprising" },
    ],
  },
}
